version: "3.8"

services:
  hello-express:
    volumes:
      - ./src:/app/src:ro

    build:
      context: .
      # args:
      #   - NODE_ENV=development
      target: development

    command:
      - start:dev

    environment:
      - NODE_ENV=development

    ports:
      - "80:80"

    env_file:
      - .env
