version: "3.8"

services:
  hello-express:
    command:
      - start

    build:
      context: .
      # args:
      #   - NODE_ENV=production
      target: production

    environment:
      - NODE_ENV=production

    ports:
      - "80:80"

    env_file:
      - .env
