version: "3.8"

services:
  hello-express:
    volumes:
      - ./src:/app/src:ro

    command:
      - start:dev

    environment:
      - NODE_ENV=development

    ports:
      - "80:80"

    env_file:
      - .env
